// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhistApi.Models;

namespace WhistApi.Migrations
{
    [DbContext(typeof(RundeContext))]
    [Migration("20190510120514_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WhistApi.Models.Runde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Beloeb");

                    b.Property<int>("Makker");

                    b.Property<int>("Melder");

                    b.Property<int>("Melding");

                    b.Property<int>("PlusId");

                    b.Property<int>("RundeNr");

                    b.Property<int>("SpilId");

                    b.Property<int>("Spiller1");

                    b.Property<int>("Spiller2");

                    b.Property<int>("Spiller3");

                    b.Property<int>("Spiller4");

                    b.Property<bool>("Vundet");

                    b.HasKey("Id");

                    b.ToTable("Runder");
                });
#pragma warning restore 612, 618
        }
    }
}
